# Generated by Django 2.2.1 on 2019-05-28 01:53

from django.db import migrations, models
import django.db.models.deletion
import herschel.apps.submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('pseudonym', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, choices=[('', 'N/A'), ('ARCH', 'Architecture & Urban Planning'), ('STAMPS', 'Art & Design'), ('ROSS', 'Business'), ('DENT', 'Dentistry'), ('EDU', 'Education'), ('ENGR', 'Engineering'), ('ENVR', 'Environment and Sustainability'), ('INFO', 'Information'), ('KINES', 'Kinesiology'), ('LAW', 'Law'), ('LSA', 'Literature, Science, and the Arts'), ('MED', 'Medicine'), ('SMTD', 'Music, Theatre & Dance'), ('NURSE', 'Nursing'), ('PHARM', 'Pharmacy'), ('SPH', 'Public Health'), ('FORD', 'Public Policy'), ('GRAD', 'Rackham School of Graduate Studies'), ('SOCW', 'Social Work')], max_length=6)),
                ('standing', models.CharField(blank=True, choices=[('', 'N/A'), ('FRESHMAN', 'Freshman'), ('SOPHOMORE', 'Sophomore'), ('JUNIOR', 'Junior'), ('SENIOR', 'Senior'), ('GRADUATE', 'Graduate'), ('STAFF', 'Staff'), ('FACULTY', 'Faculty'), ('ALUMNUS', 'Alumnus')], max_length=10)),
                ('major_field', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('POETRY', 'Poetry'), ('PROSE', 'Prose'), ('PHOTO', 'Photography'), ('VIS', 'Visual Art'), ('OTHER', 'Other')], max_length=10)),
                ('attachment', models.FileField(upload_to=herschel.apps.submissions.models._get_submission_path)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='submissions.Artist')),
            ],
        ),
    ]
